language: node_js
node_js:
  - node

before_script:
  - npm ci # Clean install all dependencies

script:
  - npm run test:unit

after_success:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  edge: true
  skip_cleanup: true
  local_dir: dist
  on:
    branch: main
